name: Sistema de Asistencia Automatizado

on:
  # Ejecución programada
  schedule:
    # Sistema de asistencia a las 10:00 UTC (05:00 Perú, UTC-5)
    - cron: '0 21 * * *'  # 10:00 diario
    # Verificación de pagos a las 11:00 UTC (06:00 Perú, UTC-5)
    - cron: '0 11 * * *'  # 11:00 diario
  
  # Permitir ejecución manual
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción a ejecutar'
        required: true
        default: 'both'
        type: choice
        options:
        - 'sistema_asistencia'
        - 'checkpagos'
        - 'both'

jobs:
  # Job para ejecutar sistema_asistencia.py
  sistema-asistencia:
    runs-on: ubuntu-latest
    if: >
      (github.event.schedule == '0 21 * * *') || 
      (github.event_name == 'workflow_dispatch' && 
       (github.event.inputs.action == 'sistema_asistencia' || github.event.inputs.action == 'both'))
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Crear archivo .env
      run: |
        echo "GOOGLE_SERVICE_ACCOUNT_FILE=sistemaasistencia-470019-3f3d35327bca.json" >> .env
        echo "GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}" >> .env
        echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
        echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> .env
    
    - name: Crear archivo de credenciales de Google
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > sistemaasistencia-470019-3f3d35327bca.json
    
    - name: Ejecutar Sistema de Asistencia
      run: |
        python sistema_asistencia.py
    
    - name: Subir reportes generados
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: reportes-asistencia-${{ github.run_number }}
        path: Reportes_Asistencia/
        retention-days: 30

  # Job para ejecutar checkpagos.py (1 hora después)
  verificacion-pagos:
    runs-on: ubuntu-latest
    needs: sistema-asistencia
    if: >
      (github.event.schedule == '0 11 * * *') || 
      (github.event_name == 'workflow_dispatch' && 
       (github.event.inputs.action == 'checkpagos' || github.event.inputs.action == 'both'))
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Crear archivo .env
      run: |
        echo "GOOGLE_SERVICE_ACCOUNT_FILE=sistemaasistencia-470019-3f3d35327bca.json" >> .env
        echo "GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}" >> .env
    
    - name: Crear archivo de credenciales de Google
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > sistemaasistencia-470019-3f3d35327bca.json
    
    - name: Ejecutar Verificación de Pagos
      run: |
        python checkpagos.py

  # Job independiente para ejecución manual solo de checkpagos
  solo-checkpagos:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.action == 'checkpagos'
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Crear archivo .env
      run: |
        echo "GOOGLE_SERVICE_ACCOUNT_FILE=sistemaasistencia-470019-3f3d35327bca.json" >> .env
        echo "GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}" >> .env
    
    - name: Crear archivo de credenciales de Google
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > sistemaasistencia-470019-3f3d35327bca.json
    
    - name: Ejecutar solo Verificación de Pagos
      run: |
        python checkpagos.py
